[package]
name = "anodized-fmt"
description = "Formatter for #[spec] annotations in Anodized"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[[bin]]
name = "anodized-fmt"
path = "src/main.rs"

[lib]
name = "anodized_fmt"
path = "src/lib.rs"

[dependencies]
anodized-core.workspace = true
clap.workspace = true
prettyplease.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
thiserror.workspace = true

crop = "0.4"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
walkdir = "2"

[dev-dependencies]
pretty_assertions.workspace = true
