[package]
name = "cargo-anodized"
description = "Cargo tool integration for Anodized"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[[bin]]
name = "cargo-anodized"
path = "src/main.rs"

[dependencies]
anodized-fmt.workspace = true
clap.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
