[package]
name = "anodized"
description.workspace = true

version.workspace = true
edition.workspace = true
rust-version.workspace = true
readme = "README.md"
repository.workspace = true
categories.workspace = true
keywords.workspace = true
license.workspace = true

[lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    "cfg(anodized_charon)",
    "cfg(anodized_discard_specs)",
    "cfg(anodized_embed_specs)",
    "cfg(anodized_panic)",
    "cfg(anodized_print)",
    "cfg(anodized_try)",
]

[features]
default = ["logic"]
logic = ["dep:anodized-logic"]

[dependencies]
anodized-logic = { workspace = true, optional = true }
anodized-macros.workspace = true

[dev-dependencies]
pollster = "0.4"
trybuild = "1.0"

[[test]]
name = "arithmetic"
required-features = ["logic"]
